### ISSUE TITLE
MongoDB connection string exposed. 

### ISSUE THREAD

**Issue by error434** [AizorStudio/93#1]
I noticed that you have exposed some of your MongoDB connection strings.
Quite a few people tend to have scrappers which scrape github repos for connection strings and then tend to wipe out the entire DB

So I would recommend you to delete this repository as a whole and then commit the files in a new one after making sure that you aren't exposing any private keys or tokens in any of the files.
Deleting the entire database and using a new one is the best solution but I don't think that is possible in your case

Make sure to keep this in mind while committing to your future repos

**Comment by rijumarwah** [comment]
Will make sure, thanks 👍
I'll be rewriting the whole code anyways, it's a huge mess right now
